"use client";

import { useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { Part, StoDetail, StoHeader, Tag, TagDetail, User, ViewMode } from '../lib/types';
import { sampleParts, sampleTagDetails, sampleTags, sampleUsers } from '../lib/sampleData';

type Menu = 'DASHBOARD'|'INPUT'|'CHECK'|'RESUME'|'MASTER';
const key = (k:string)=>`sto_app_${k}`;
const today = ()=>new Date().toISOString().slice(0,10);
const nowIso = ()=>new Date().toISOString();
const timeOnly = (iso:string)=> new Date(iso).toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'});
const fmtDateTime = (iso?:string)=> iso ? new Date(iso).toLocaleString('id-ID') : '-';
const uid = (p='ID') => `${p}${Date.now()}${Math.floor(Math.random()*999)}`;

function load<T>(name:string, fallback:T):T{ if(typeof window==='undefined') return fallback; const raw=localStorage.getItem(key(name)); return raw?JSON.parse(raw):fallback; }
function save<T>(name:string, data:T){ localStorage.setItem(key(name), JSON.stringify(data)); }
function safeCalc(expr:string){
  const clean = expr.replace(/×/g,'*').replace(/x/gi,'*').replace(/,/g,'.').replace(/[^0-9+\-*/().\s]/g,'');
  if(!clean.trim()) return 0;
  // eslint-disable-next-line no-new-func
  const val = Function(`"use strict"; return (${clean})`)();
  return Number.isFinite(val) ? Math.max(0, Math.floor(val)) : 0;
}

export default function Home(){
  const [users,setUsers]=useState<User[]>(sampleUsers);
  const [parts,setParts]=useState<Part[]>(sampleParts);
  const [tags,setTags]=useState<Tag[]>(sampleTags);
  const [tagDetails,setTagDetails]=useState<TagDetail[]>(sampleTagDetails);
  const [stos,setStos]=useState<StoHeader[]>([]);
  const [user,setUser]=useState<User|null>(null);
  const [menu,setMenu]=useState<Menu>('DASHBOARD');

  useEffect(()=>{ const loadedUsers=load('users',sampleUsers).map((u:any)=>({...u,password:u.password||'1234',signatureName:u.signatureName||u.fullName,active:u.active!==false})); setUsers(loadedUsers); setParts(load('parts',sampleParts)); setTags(load('tags',sampleTags)); setTagDetails(load('tagDetails',sampleTagDetails)); setStos(load('stos',[])); const u=load<User|null>('session',null); setUser(u ? ({...u,password:(u as any).password||'1234',signatureName:(u as any).signatureName||u.fullName,active:u.active!==false} as User) : null); },[]);
  useEffect(()=>{ save('users',users) },[users]); useEffect(()=>{ save('parts',parts) },[parts]); useEffect(()=>{ save('tags',tags) },[tags]); useEffect(()=>{ save('tagDetails',tagDetails) },[tagDetails]); useEffect(()=>{ save('stos',stos) },[stos]);

  if(!user) return <Login users={users} onLogin={(u)=>{setUser(u); save('session',u)}} />;

  return <main className="app">
    <div className="topbar no-print">
      <div className="brand"><div><div className="logo">STO Web App</div><div className="sub">Mobile-first Stock Taking Tag</div></div><div className="row"><span className="pill">{user.fullName} / {user.role}</span><button className="btn small red" onClick={()=>{localStorage.removeItem(key('session')); setUser(null)}}>Logout</button></div></div>
      <div className="nav">
        {(['DASHBOARD','INPUT','CHECK','RESUME','MASTER'] as Menu[]).map(m=><button key={m} className={menu===m?'active':''} onClick={()=>setMenu(m)}>{m}</button>)}
      </div>
    </div>
    {menu==='DASHBOARD' && <Dashboard tags={tags} stos={stos}/>} 
    {menu==='INPUT' && <InputSto user={user} parts={parts} tags={tags} tagDetails={tagDetails} stos={stos} setStos={setStos}/>} 
    {menu==='CHECK' && <CheckSto user={user} stos={stos} setStos={setStos}/>} 
    {menu==='RESUME' && <Resume parts={parts} stos={stos} setStos={setStos}/>} 
    {menu==='MASTER' && <Master parts={parts} setParts={setParts} tags={tags} setTags={setTags} tagDetails={tagDetails} setTagDetails={setTagDetails} users={users} setUsers={setUsers}/>} 
  </main>;
}

function Login({users,onLogin}:{users:User[],onLogin:(u:User)=>void}){
  const [username,setUsername]=useState('agung');
  const [password,setPassword]=useState('1234');
  return <div className="login"><div className="card"><h1>Login STO</h1><p className="muted">Demo login: <b>agung</b>, <b>leader</b>, atau <b>admin</b>. Password default: <b>1234</b>.</p><label>Username</label><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="username"/><label>Password</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="password"/><br/><br/><button className="btn primary" style={{width:'100%'}} onClick={()=>{const u=users.find(x=>x.username.toLowerCase()===username.toLowerCase() && x.password===password && x.active); if(u) onLogin(u); else alert('Username / password salah atau user tidak aktif')}}>Masuk</button></div></div>
}

function Dashboard({tags,stos}:{tags:Tag[],stos:StoHeader[]}){ const counted=stos.filter(s=>s.status==='COUNTED'||s.status==='CHECKED'||s.status==='CLOSED').length; const checked=stos.filter(s=>s.status==='CHECKED'||s.status==='CLOSED').length; return <div className="grid"><Stat t="Total Tag" v={tags.length}/><Stat t="Sudah Count" v={counted}/><Stat t="Belum Count" v={Math.max(tags.length-counted,0)}/><Stat t="Sudah Check Leader" v={checked}/></div> }
function Stat({t,v}:{t:string,v:number}){return <div className="card span-3"><div className="sub">{t}</div><div className="stat">{v}</div></div>}

function InputSto({user,parts,tags,tagDetails,stos,setStos}:{user:User,parts:Part[],tags:Tag[],tagDetails:TagDetail[],stos:StoHeader[],setStos:(s:StoHeader[])=>void}){
  const [date,setDate]=useState(today()); const [area,setArea]=useState(user.defaultArea||'RM'); const [tagNo,setTagNo]=useState(tags[0]?.tagNo||''); const [mode,setMode]=useState<ViewMode>(user.role==='OPERATOR'?'INPUT':'FULL'); const [start,setStart]=useState(nowIso()); const [details,setDetails]=useState<StoDetail[]>([]);
  useEffect(()=>{ if(tagNo){ setStart(nowIso()); const ds=tagDetails.filter(td=>td.tagNo===tagNo&&td.active).sort((a,b)=>a.sequenceNo-b.sequenceNo).map(td=>parts.find(p=>p.partNo===td.partNo)).filter(Boolean).map((p:any)=>({ id:uid('D'), partNo:p.partNo, fiiId:p.fiiId, partName:p.partName, qtyPerBox:Number(p.qtyPerBox)||0, boxQty:0, fractionQty:0, grandTotal:0, calculationNote:'', leaderCheckStatus:false })); setDetails(ds); } },[tagNo,parts,tagDetails]);
  const update=(id:string,patch:Partial<StoDetail>)=>setDetails(ds=>ds.map(d=>{ if(d.id!==id) return d; const n={...d,...patch}; n.grandTotal=(Number(n.qtyPerBox)||0)*(Number(n.boxQty)||0)+(Number(n.fractionQty)||0); return n; }));
  const filled=details.filter(d=>d.boxQty>0 || d.fractionQty>0).length;
  const submit=()=>{ const end=nowIso(); const dur=Math.max(0, Math.round(((new Date(end).getTime()-new Date(start).getTime())/3600000)*10)/10); const sto:StoHeader={ stoId:uid('STO'), stoNo:`STO-${date.replaceAll('-','')}-${tagNo}`, stoDate:date, area, tagNo, creatorUserId:user.id, creatorName:user.fullName, startTime:start, endTime:end, durationHour:dur, status:'COUNTED', creatorSignedAt:end, details}; setStos([sto,...stos]); alert('STO tersimpan dan signature creator sudah dibuat.'); };
  return <div className="grid"><div className="card span-12"><div className="between"><div><h2 className="title">Input STO</h2><div className="sub">Tag {tagNo} • Progress {filled}/{details.length} • Start {timeOnly(start)}</div></div><button className="btn green" onClick={submit}>Simpan</button></div><div className="grid"><div className="span-3"><label>Tanggal</label><input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div><div className="span-3"><label>Area</label><select value={area} onChange={e=>setArea(e.target.value)}><option>RM</option><option>WIP</option><option>FG</option><option>P</option><option>S</option></select></div><div className="span-3"><label>Tag Number</label><select value={tagNo} onChange={e=>setTagNo(e.target.value)}>{tags.map(t=><option key={t.tagNo}>{t.tagNo}</option>)}</select></div><div className="span-3"><label>Mode</label><select value={mode} onChange={e=>setMode(e.target.value as ViewMode)}><option value="INPUT">Input Mode</option><option value="FULL">Full Mode</option></select></div></div></div><div className="span-12">{details.map((d,i)=><StoItem key={d.id} index={i+1} d={d} mode={mode} update={update}/>)}</div></div>
}
function StoItem({d,index,mode,update}:{d:StoDetail,index:number,mode:ViewMode,update:(id:string,p:Partial<StoDetail>)=>void}){ const [show,setShow]=useState(false); const [calc,setCalc]=useState(d.calculationNote); const [calcOpen,setCalcOpen]=useState(false); const ok=d.boxQty>0||d.fractionQty>0; const step=(field:'boxQty'|'fractionQty',n:number)=>update(d.id,{[field]:Math.max(0,Number(d[field])+n)} as any); return <div className={`item-card ${ok?'ok':'warn'}`}><div className="between"><div><b>{index}. FII ID: {d.fiiId}</b>{mode==='FULL'&&<div className="sub">{d.partNo} • {d.partName} • Qty/Box {d.qtyPerBox}</div>}</div><span className="total">{d.grandTotal.toLocaleString('id-ID')}</span></div><div className="qtyline"><b>Box</b><div className="stepper"><button onClick={()=>step('boxQty',-1)}>-1</button><input type="number" value={d.boxQty} onChange={e=>update(d.id,{boxQty:Number(e.target.value)||0})}/><button onClick={()=>step('boxQty',1)}>+1</button><button onClick={()=>step('boxQty',5)}>+5</button><button onClick={()=>step('boxQty',10)}>+10</button><button onClick={()=>update(d.id,{boxQty:0})}>Reset</button></div></div><div className="qtyline"><b>Fraction</b><div className="stepper"><button onClick={()=>step('fractionQty',-1)}>-1</button><input type="number" value={d.fractionQty} onChange={e=>update(d.id,{fractionQty:Number(e.target.value)||0})}/><button onClick={()=>step('fractionQty',1)}>+1</button><button onClick={()=>step('fractionQty',5)}>+5</button><button onClick={()=>step('fractionQty',10)}>+10</button><button onClick={()=>update(d.id,{fractionQty:0})}>Reset</button></div></div><div className="row" style={{marginTop:10}}><button className="btn small ghost" onClick={()=>setCalcOpen(!calcOpen)}>Calc</button><button className="btn small" onClick={()=>setShow(!show)}>Detail</button></div>{calcOpen&&<div className="calc-box"><label>Kalkulator Box, contoh: 3 x 10 + 4</label><input value={calc} onChange={e=>setCalc(e.target.value)} placeholder="3 x 10 + 4"/><div className="row" style={{marginTop:8}}><b>Hasil: {safeCalc(calc)}</b><button className="btn small primary" onClick={()=>update(d.id,{boxQty:safeCalc(calc), calculationNote:calc})}>Gunakan</button></div></div>}{show&&<div className="calc-box"><div>Part Number: <b>{d.partNo}</b></div><div>Part Name: <b>{d.partName}</b></div><div>Qty/Box: <b>{d.qtyPerBox}</b></div><div>Note: {d.calculationNote||'-'}</div></div>}</div> }

function CheckSto({user,stos,setStos}:{user:User,stos:StoHeader[],setStos:(s:StoHeader[])=>void}){ const list=stos.filter(s=>s.status==='COUNTED'); const updateSto=(sto:StoHeader)=>setStos(stos.map(s=>s.stoId===sto.stoId?sto:s)); const checkAll=(sto:StoHeader)=>{ const at=nowIso(); updateSto({...sto,status:'CHECKED',leaderUserId:user.id,leaderName:user.fullName,leaderSignedAt:at,details:sto.details.map(d=>({...d,leaderCheckStatus:true,leaderCheckedBy:user.fullName,leaderCheckedAt:at}))});}; return <div className="grid"><div className="card span-12"><h2>Leader Check</h2><p className="muted">Check per item atau OK per Tag.</p></div>{list.map(sto=><div className="card span-12" key={sto.stoId}><div className="between"><div><b>{sto.tagNo}</b> • {sto.creatorName} • {sto.details.length} item</div><button className="btn green" onClick={()=>checkAll(sto)}>Check OK Per Tag</button></div><div className="table-wrap" style={{marginTop:10}}><table><thead><tr><th>OK</th><th>FII</th><th>Part</th><th>Total</th></tr></thead><tbody>{sto.details.map(d=><tr key={d.id}><td><input type="checkbox" checked={d.leaderCheckStatus} onChange={e=>{const at=nowIso(); updateSto({...sto,details:sto.details.map(x=>x.id===d.id?{...x,leaderCheckStatus:e.target.checked,leaderCheckedBy:user.fullName,leaderCheckedAt:at}:x)})}}/></td><td>{d.fiiId}</td><td>{d.partNo}<br/><span className="muted">{d.partName}</span></td><td>{d.grandTotal}</td></tr>)}</tbody></table></div></div>)}</div> }

function Resume({parts,stos,setStos}:{parts:Part[],stos:StoHeader[],setStos:(s:StoHeader[])=>void}){ const exportExcel=()=>{ const rows=stos.flatMap(s=>s.details.map(d=>{const p=parts.find(x=>x.partNo===d.partNo); return {'FII ID':d.fiiId,'PART NUMBER':d.partNo,'PART NAME':d.partName,'QTY(PCS/KG)':d.grandTotal,'AREA':p?.area||s.area,'LOKASI & NO RACK':p?.rackNo||'','DEPT':p?.dept||'','WAKTU':s.durationHour||0,'TAG':s.tagNo,'PIC':s.creatorName,'BOX':d.boxQty,'FRACTION':d.fractionQty,'CALCULATION NOTE':d.calculationNote,'STATUS':s.status}})); const ws=XLSX.utils.json_to_sheet(rows); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,'STO Report'); XLSX.writeFile(wb,`STO_Report_${today()}.xlsx`);}; return <div className="grid"><div className="card span-12"><div className="between"><div><h2>Resume STO</h2><p className="muted">Export Excel dan print audit.</p></div><button className="btn primary" onClick={exportExcel}>Export Excel</button></div></div>{stos.map(sto=><div className="card span-12" key={sto.stoId}><div className="between no-print"><div><b>{sto.stoNo}</b> <span className={`badge ${sto.status.toLowerCase()}`}>{sto.status}</span><div className="sub">{sto.stoDate} • Tag {sto.tagNo} • PIC {sto.creatorName} • Waktu {sto.durationHour||0}</div></div><button className="btn" onClick={()=>window.print()}>Print</button></div><AuditPrint sto={sto} parts={parts}/></div>)}</div> }
function AuditPrint({sto,parts}:{sto:StoHeader,parts:Part[]}){return <div><div className="print-only audit-title">STOCK TAKING TAG</div><div className="grid"><div className="span-6"><b>Date:</b> {sto.stoDate}<br/><b>Area:</b> {sto.area}<br/><b>Tag:</b> {sto.tagNo}</div><div className="span-6"><b>PIC:</b> {sto.creatorName}<br/><b>Start:</b> {fmtDateTime(sto.startTime)}<br/><b>End:</b> {fmtDateTime(sto.endTime)}<br/><b>Duration:</b> {sto.durationHour||0}</div></div><div className="table-wrap" style={{marginTop:10}}><table><thead><tr><th>No</th><th>Part Number</th><th>FII ID</th><th>Part Name</th><th>Qty/Box</th><th>Jumlah Box</th><th>Total</th><th>Fraction</th><th>Grand Total</th></tr></thead><tbody>{sto.details.map((d,i)=><tr key={d.id}><td>{i+1}</td><td>{d.partNo}</td><td>{d.fiiId}</td><td>{d.partName}</td><td>{d.qtyPerBox}</td><td>{d.boxQty}</td><td>{d.qtyPerBox*d.boxQty}</td><td>{d.fractionQty}</td><td>{d.grandTotal}</td></tr>)}</tbody></table></div><div className="grid"><div className="span-6 signature">Creator<br/><b>{sto.creatorName}</b><br/>{fmtDateTime(sto.creatorSignedAt)}</div><div className="span-6 signature">Leader<br/><b>{sto.leaderName||'-'}</b><br/>{fmtDateTime(sto.leaderSignedAt)}</div></div></div>}

function Master({parts,setParts,tags,setTags,tagDetails,setTagDetails,users,setUsers}:{parts:Part[],setParts:(p:Part[])=>void,tags:Tag[],setTags:(t:Tag[])=>void,tagDetails:TagDetail[],setTagDetails:(t:TagDetail[])=>void,users:User[],setUsers:(u:User[])=>void}){ 
  const [tab,setTab]=useState<'Part'|'Tag'|'TagDetail'|'User'>('Part');
  const exportData=(name:string,data:any[])=>{const ws=XLSX.utils.json_to_sheet(data); const wb=XLSX.utils.book_new(); XLSX.utils.book_append_sheet(wb,ws,name); XLSX.writeFile(wb,`Master_${name}.xlsx`)}; 
  const importExcel=(e:any,type:string)=>{const file=e.target.files?.[0]; if(!file) return; const reader=new FileReader(); reader.onload=(ev)=>{const wb=XLSX.read(ev.target?.result,{type:'binary'}); const rows:any[]=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]]); if(type==='Part'){const mapped=rows.map(r=>({partNo:String(r['Part Number']||r.partNo||''),fiiId:String(r['FII ID']||r.fiiId||''),partName:String(r['Part Name']||r.partName||''),qtyPerBox:Number(r['Qty Per Box']||r.qtyPerBox||0),area:String(r.Area||r.area||''),rackNo:String(r['Rack Number']||r.rackNo||''),dept:String(r.Dept||r.dept||''),active:String(r.Active||'Y')!=='N'})).filter(r=>r.partNo); setParts(mapped);} if(type==='Tag'){setTags(rows.map(r=>({tagNo:String(r['Tag Number']||r.tagNo),area:String(r.Area||r.area||'RM'),description:String(r.Description||r.description||''),active:String(r.Active||'Y')!=='N'})).filter(r=>r.tagNo));} if(type==='TagDetail'){setTagDetails(rows.map((r,i)=>({id:uid('TD'),tagNo:String(r['Tag Number']||r.tagNo),partNo:String(r['Part Number']||r.partNo),sequenceNo:Number(r['Sequence No']||r.sequenceNo||i+1),active:true})).filter(r=>r.tagNo&&r.partNo));} if(type==='User'){setUsers(rows.map((r,i)=>({id:String(r.ID||r.id||uid('U')),username:String(r.Username||r.username||''),password:String(r.Password||r.password||'1234'),fullName:String(r['Full Name']||r.fullName||''),role:String(r.Role||r.role||'OPERATOR').toUpperCase() as any,defaultArea:String(r['Default Area']||r.defaultArea||'RM'),signatureName:String(r['Signature Name']||r.signatureName||r['Full Name']||r.fullName||''),active:String(r.Active||'Y')!=='N'})).filter(r=>r.username));}}; reader.readAsBinaryString(file);}; 
  const data=tab==='Part'?parts:tab==='Tag'?tags:tab==='TagDetail'?tagDetails:users;
  return <div className="grid"><div className="card span-12"><div className="row"><button className="btn" onClick={()=>setTab('Part')}>Part</button><button className="btn" onClick={()=>setTab('Tag')}>Tag</button><button className="btn" onClick={()=>setTab('TagDetail')}>Tag Detail</button><button className="btn" onClick={()=>setTab('User')}>User Management</button><button className="btn primary" onClick={()=>exportData(tab,data as any[])}>Export {tab}</button><label className="btn ghost">Import {tab}<input type="file" accept=".xlsx,.xls" style={{display:'none'}} onChange={e=>importExcel(e,tab)}/></label></div></div>{tab==='User'&&<UserManagement users={users} setUsers={setUsers}/>}<div className="card span-12"><div className="table-wrap"><table><thead><tr>{Object.keys((data as any[])[0]||{}).map(k=><th key={k}>{k}</th>)}</tr></thead><tbody>{(data as any[]).map((r,i)=><tr key={i}>{Object.keys((data as any[])[0]||{}).map(k=><td key={k}>{k.toLowerCase().includes('password')?'******':String(r[k])}</td>)}</tr>)}</tbody></table></div></div></div> 
}

function UserManagement({users,setUsers}:{users:User[],setUsers:(u:User[])=>void}){
  const empty:User={id:'',username:'',password:'1234',fullName:'',role:'OPERATOR',defaultArea:'RM',signatureName:'',active:true};
  const [form,setForm]=useState<User>(empty);
  const edit=(u:User)=>setForm({...u,password:u.password||'1234'});
  const saveUser=()=>{
    if(!form.username || !form.fullName){ alert('Username dan Full Name wajib diisi'); return; }
    const dup=users.some(u=>u.username.toLowerCase()===form.username.toLowerCase() && u.id!==form.id);
    if(dup){ alert('Username sudah dipakai'); return; }
    const payload={...form,id:form.id||uid('U'),signatureName:form.signatureName||form.fullName,password:form.password||'1234'};
    setUsers(form.id ? users.map(u=>u.id===form.id?payload:u) : [payload,...users]);
    setForm(empty);
  };
  const resetPass=(u:User)=>{ if(confirm(`Reset password ${u.username} ke 1234?`)) setUsers(users.map(x=>x.id===u.id?{...x,password:'1234'}:x)); };
  const toggle=(u:User)=>setUsers(users.map(x=>x.id===u.id?{...x,active:!x.active}:x));
  const remove=(u:User)=>{ if(confirm(`Hapus user ${u.username}?`)) setUsers(users.filter(x=>x.id!==u.id)); };
  return <div className="card span-12"><h2 className="title">User Management</h2><p className="muted">Admin bisa tambah/edit user, role, default area, status aktif, dan reset password.</p><div className="grid"><div className="span-3"><label>Username</label><input value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/></div><div className="span-3"><label>Password</label><input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div><div className="span-3"><label>Full Name</label><input value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value,signatureName:e.target.value})}/></div><div className="span-3"><label>Role</label><select value={form.role} onChange={e=>setForm({...form,role:e.target.value as any})}><option>ADMIN</option><option>OPERATOR</option><option>LEADER</option></select></div><div className="span-3"><label>Default Area</label><select value={form.defaultArea} onChange={e=>setForm({...form,defaultArea:e.target.value})}><option>RM</option><option>WIP</option><option>FG</option><option>P</option><option>S</option></select></div><div className="span-3"><label>Signature Name</label><input value={form.signatureName||''} onChange={e=>setForm({...form,signatureName:e.target.value})}/></div><div className="span-3"><label>Status</label><select value={form.active?'Y':'N'} onChange={e=>setForm({...form,active:e.target.value==='Y'})}><option value="Y">Active</option><option value="N">Inactive</option></select></div><div className="span-3"><label>Aksi</label><div className="row"><button className="btn green" onClick={saveUser}>{form.id?'Update':'Tambah'}</button><button className="btn" onClick={()=>setForm(empty)}>Clear</button></div></div></div><div className="table-wrap" style={{marginTop:12}}><table><thead><tr><th>Username</th><th>Full Name</th><th>Role</th><th>Area</th><th>Signature</th><th>Active</th><th>Aksi</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.username}</td><td>{u.fullName}</td><td>{u.role}</td><td>{u.defaultArea}</td><td>{u.signatureName||u.fullName}</td><td>{u.active?'Y':'N'}</td><td><div className="row"><button className="btn small" onClick={()=>edit(u)}>Edit</button><button className="btn small ghost" onClick={()=>resetPass(u)}>Reset PW</button><button className="btn small orange" onClick={()=>toggle(u)}>{u.active?'Nonaktif':'Aktifkan'}</button><button className="btn small red" onClick={()=>remove(u)}>Hapus</button></div></td></tr>)}</tbody></table></div></div>
}
